---
title: "Untitled"
author: "Alexander Ng"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tigris)
library(sf)
library(tidyverse)
library(mapview)
library(readxl)
library(spdep)
library(spatialreg)
library(survey)

sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[sf_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

temp <- tempfile()
download.file("https://www2.census.gov/programs-surveys/acs/data/pums/2019/1-Year/csv_hca.zip",destfile = temp)

pums_hca_2019_1yr <- read_csv(unzip(temp,"psam_h06.csv"))

unlink(temp)

data <- pums_hca_2019_1yr %>%
  filter(PUMA %in% sf_pumas$PUMACE10) %>%
  mutate(
    HINCP = as.numeric(HINCP),
    TEN = factor(TEN),
    MV = factor(MV)
  ) %>%
  select(
    HINCP,
    TEN,
    MV,
    starts_with("WGTP")
  ) %>%
  filter_all(all_vars(!is.na(.))) #removes any NA records

design <- svrepdesign(
  data = data,
  type = "ACS", 
  repweights = data[ ,5:84],
  weights = ~WGTP
)

model <- svyglm(
  formula = HINCP ~ TEN + MV,
  family = gaussian(), #makes glm function work as a lm function
  design = design
)

summary(model)

weighted_model <- data %>% 
  lm(
    formula = HINCP ~ TEN + MV,
    data = ., #period refers to data in pipeline
    weights = WGTP
  )

summary(weighted_model)

replicates_model <-
  1:80 %>%
  map_dfr(function(x){ #x is dummy variable
    
    data %>%
      rename(replicate = paste0("WGTP", x)) %>%
      lm(
    formula = HINCP ~ TEN + MV,
    data = ., 
    weights = replicate
      ) %>%
      .$coefficients %>%
      as.data.frame() %>%
    rownames_to_column()
    
  })

weight_model_summary <-replicates_model %>%
  rename(replicate = ".") %>%
  left_join(
    weighted_model$coefficients %>%
      as.data.frame() %>%
      rownames_to_column() %>%
      rename(base = ".")
  ) %>%
  group_by(rowname) %>%
  summarize(
    stderror = sqrt(4/80*sum(base-replicate)^2),
    base = first(base)
  ) %>%
  select(
    rowname,
    base,
    stderror
  )

```

